@Krabby.Api_HostAddress = http://localhost:5206

###  Anime lookup
GET {{Krabby.Api_HostAddress}}/api/anidb/aid/19699
Accept: application/json

###

### AniDB Episode AID test
GET {{Krabby.Api_HostAddress}}/api/anidb/aid/loaded
Accept: application/json

###

### AniDB Episode AID test
GET {{Krabby.Api_HostAddress}}/api/anidb/aid/episodes/get
Accept: application/json

###

### AniDB Episode AID test
GET {{Krabby.Api_HostAddress}}/api/anidb/aid/episodes/status/01a2d7e4-c9ef-431c-8e1a-c36bc280d0e0
Accept: application/json

###

### AniDB login status test
GET {{Krabby.Api_HostAddress}}/api/anidb/login/status
Accept: application/json

###

### AniDB login test
GET {{Krabby.Api_HostAddress}}/api/anidb/login/execute
Accept: application/json

###
