@Krabby.Api_HostAddress = http://localhost:5206

###  Anime lookup
GET {{Krabby.Api_HostAddress}}/api/anidb/aid/19042
Accept: application/json

###

### AniDB Episode AID test
GET {{Krabby.Api_HostAddress}}/api/anidb/aid/loaded
Accept: application/json

###

### AniDB Episode AID test
GET {{Krabby.Api_HostAddress}}/api/anidb/aid/episodes/get
Accept: application/json

###

### AniDB Episode AID test
GET {{Krabby.Api_HostAddress}}/api/anidb/aid/episodes/status/e8568f9a-257d-4f47-b4f1-7ac4e9994dc1
Accept: application/json

###

### AniDB login status test
GET {{Krabby.Api_HostAddress}}/api/anidb/login/status
Accept: application/json

###

### AniDB login test
GET {{Krabby.Api_HostAddress}}/api/anidb/login/execute
Accept: application/json

###

### AniDB API Wrapper alive
GET {{Krabby.Api_HostAddress}}/api/anidb/alive
Accept: application/json

###
